user_name_length_max: 50
user_email_length_max: 250
user_pass_length_min: 6
gravatar_size: 80
remember_me: 1
gravatar_user_size: 50
split_page: 10
expired_time: 2
content_length_max: 140
picture_max_size: 5
resize_to_limit: [400, 400]
